TARGET = libc
OBJS =	vsprintf.o abs.o atoi.o errno.o memchr.o memcmp.o memcpy.o memmove.o \
		memset.o qsort.o rand.o sprintf.o strcat.o strchr.o strcmp.o strcpy.o \
		strcspn.o strlen.o strncat.o strncmp.o strncpy.o strpbrk.o strrchr.o \
		strspn.o strstr.o strtol.o strtoul.o strtoul0.o 

include ../../mkfiles/libs.mk
